[package]
name = "lua-mutation-test"
version = "0.1.0"
edition = "2021"
description = "A mutation testing tool for Lua, written in Rust."
repository = "https://github.com/rcasia/lua-mutation-test"
license = "Elastic-2.0"
readme = "README.md"
keywords = ["lua", "mutation-testing", "testing"]
categories = ["development-tools::testing"]

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
tree-sitter = "0.25.3"
tree-sitter-lua = { path = "./tree-sitter-lua", version = "0.5.0" }
glob = "0.3"

[dev-dependencies]
tempfile = "3"

[[bin]]
name = "lua-mutation-test"
path = "src/main.rs"


